// resources/js/Pages/Auth/Login.vue
<script setup>
import GuestLayout from '@/layouts/GuestLayout.vue';
import { Link } from '@inertiajs/vue3';
</script>

<template>
    <GuestLayout>
        <Link :href="route('department.index')" class="bg-red-500">
            Go to Department page
        </Link>
        <p>Login page</p>
    </GuestLayout>
</template>

// resources/js/Pages/Auth/Login.jsx
import GuestLayout from '@/layouts/GuestLayout';
import { Link } from '@inertiajs/react';
import { BASE_URL } from '@/config';
export default function Login() {
  return (
    <GuestLayout>
      <div>
        <Link href={BASE_URL + '/department'}> Department </Link>
        <Link href={route('department.index')}> Dept v2 </Link>

        <p>login page</p>
      </div>
    </GuestLayout>
  );
}
